heat_template_version: 2016-04-08

# Ceph Monitors

parameters:

  name:
    type: string

  key_name:
    type: string
  
  image_name:
    type: string
  
  flavor_name:
    type: string

  net_ceph_external_id:
    type: string
  
  sub_ceph_external_id:
    type: string

  net_ceph_internal_id:
    type: string
  
  sub_ceph_internal_id:
    type: string

resources:
  ceph_monitor:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_name }
      key_name: { get_param: key_name }
      user_data_format: RAW
      user_data: |
        #cloud-config
        ssh_pwauth: True
        password: passw0rd
        chpasswd:
          list: |
            centos:password1
          expire: False
        final_message: "The system is finally up, after $UPTIME seconds"
      networks:
        - port: { get_resource: port_ceph_mon_ext }
        - port: { get_resource: port_ceph_mon_int }

  port_ceph_mon_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net_ceph_external_id }
      fixed_ips:
        - subnet_id: { get_param: sub_ceph_external_id }

  port_ceph_mon_int:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: net_ceph_internal_id }
      fixed_ips:
        - subnet_id: { get_param: sub_ceph_internal_id }

outputs:
  instance_networks:
    description: The IP addresses of the deployed instance
    value: { get_resource: port_ceph_mon_ext }
